ボウリングのスコア計算プログラムオブジェクト指向版
its532/ruby-practices pull request #1
Opened 2021-11-18 07:54 UTC by its532

2021-11-18 08:11 UTC, its532 commented
フォルダ配下間違っていたので、ファイルを移行しました

2021-11-18 09:26 UTC, ikaruga777 commented on 07.bowling_object/frame.rb
> +  def spere?
`spare` かも? https://eow.alc.co.jp/search?q=spare

2021-11-18 09:26 UTC, ikaruga777 commented on 07.bowling_object/game.rb
> +  def frame_ary
`ary` は array の略だと思うのですが、変数名やメソッド名は省略せずに記載するのが良いです。また、 array かどうかはRubyだと複数形の名前で表現されることが多いので、それらの名前が使えないか検討されると良いと思います。

2021-11-19 08:41 UTC, its532 commented on 07.bowling_object/game.rb
> +  def frames
この変数名良いのが思い当たらず...
申し少し具体的になれば良いなと思っているのですが、あれば教えてください:bow:

2021-11-19 08:41 UTC, its532 commented on 07.bowling_object/game.rb
> +  def frame_instances
> この変数名良いのが思い当たらず...
> 申し少し具体的になれば良いなと思っているのですが、あれば教えてください:bow:

こちらも同様に

2021-11-19 08:45 UTC, its532 commented
@ikaruga777 
指摘いただいた箇所の修正いたしましたー！

あとあ追加でテストの作成と、shotクラスのscoreにはGが入らなさそうだったので一部コード削除しました。
（こちらのページにある実行例を見ても`0`と記述されていたためそう判断しました
https://bootcamp.fjord.jp/practices/210）

これで一旦、課題提出しようと思います！

2021-11-22 03:14 UTC, ikaruga777 commented on 07.bowling_object/game.rb
> +  def frames
@its532 こちら解決するために質問するのですが、 `frames` と `frame_instances` の違いってなんでしょうか? それぞれなんのために必要かがわかると、より良いアドバイスができそうです。

2021-11-22 03:57 UTC, ikaruga777 reviewed
@its532 スコア計算自体はうまくできそうに見えます。処理の中身についていくつかコメントしました。

PRのDescriptionの実行方法が違ってそうなので修正されると良さそうです。

2021-11-22 03:57 UTC, ikaruga777 commented on 07.bowling_object/game.rb
> +      frame_instances.push(Frame.new(*frame))
`Game#total_score` を呼ぶたびに `Frame` クラスのインスタンスを作っているように見えるので、不要なオブジェクト生成は避けたいですね。

`Game.new` の後、スコアが変わらないことが分かりきっているのでしたら、以下のように `||=` を使うと
- 初回の呼び出しでは変数の値が `nil` なので `frames.each` を実行して `@frame_instances` に代入する
- 二度目以降の呼び出しでは代入した結果が存在するのでその値をそのまま返す

といったことができます。

```ruby
@frame_instances ||= frames.each do |frame|
...
```

2021-11-22 03:57 UTC, ikaruga777 commented on 07.bowling_object/game.rb
> +    score_ary = @game.split(",")
`score_ary` の変数名を考え直したい気持ちがあります。説明できるものでなければ、一時変数を使わずに `@game.split(",").each do` と書いても良いと思います。

2021-11-22 03:57 UTC, ikaruga777 commented on 07.bowling_object/game.rb
> +    score_ary.each do |sa|
`sa` ってどういう変数ですか? 🤚

2021-11-22 03:57 UTC, ikaruga777 commented on 07.bowling_object/game.rb
> +    @game = pin
スコアの文字列であるというのが変数名で説明できると良さそうですかね。 (自分も今頭捻ってるところです)

2021-11-22 03:57 UTC, ikaruga777 commented on 07.bowling_object/game.rb
> +    frame_instances.each_with_index do |frame, i|
`add_strike_points` もなのですが、ストライクの計算でどのフレームを見に行くかの処理についてもう少しシンプルに書けそうと思いました。

2021-11-22 06:49 UTC, komagata requested changes
同じコミットメッセージが続いているのでもし同じ趣旨の作業が二つのコミットに分かれているのならばsquashなどして整えてみてください〜

<img width="317" alt="スクリーンショット 2021-11-22 15 38 39" src="https://user-images.githubusercontent.com/16577/142815500-04e0046d-c278-46ed-8b03-38272bfc94ca.png">

2021-11-22 06:49 UTC, komagata commented on 07.bowling_object/bowling.rb
> +require_relative './game'
`require_relative`を使うのであればこのパス指定はおかしいかもです。
require_relativeがどんなもので何のために使うのか調べてみると良いかもです〜。

2021-11-22 06:49 UTC, komagata commented on 07.bowling_object/frame.rb
> +  attr_reader :first_shot, :second_shot
APIとして、ここに`third_shot`はなくて大丈夫ですかね？

2021-11-22 06:49 UTC, komagata commented on 07.bowling_object/frame.rb
> +    [first_shot.score + second_shot.score + @third_shot.score].sum
`@shots`のようにArrayがあれば

```ruby
@shots.sum(:&score)
```

とかで行けていいかもです〜

2021-11-22 06:49 UTC, komagata commented on 07.bowling_object/shot.rb
> +  end
```suggestion
  def score
    @mark == 'X' ? 10 : @mark.to_i
  end
```

```suggestion

```

2021-11-22 06:49 UTC, komagata commented on 07.bowling_object/game.rb
> +  def frame_instances
全部丸投げして聞いちゃうと勉強にならないかもなので、もうちょっと考えてみて、今まで考えた思考の流れなどを提示した上で聞いてみるといいかもです〜

（こういう候補を考えたけどこういう理由で却下していたなど）

2021-11-22 06:50 UTC, komagata commented
@its rubocop（rubocop-fjord）を通すようにお願いします〜

2021-11-24 02:05 UTC, its532 commented on 07.bowling_object/game.rb
> +  def frames
`frames`は入力された数字をフレームごとに配列(frame)を生成し大配列(frames)に格納している
例
```
$ ruby bowling.rb 6,4,3,5,X,3,1,X,X,X,X,X,X,X,9
[["6", "4"], ["3", "5"], ["X"], ["3", "1"], ["X"], ["X"], ["X"], ["X"], ["X"], ["X", "X", "9"]]
```

`frame_instances`は上記で作成した`frames`をもとにFrameクラスのインスタンスを作成して、配列に格納する
例
```
$ ruby bowling.rb 6,4,3,5,X,3,1,X,X,X,X,X,X,X,9
[#<Frame:0x00007f9c878440b0 @first_shot=#<Shot:0x00007f9c87844010 @mark="6">, @second_shot=#<Shot:0x00007f9c87833fa8 @mark="4">, @third_shot=#<Shot:0x00007f9c87833f58 @mark=nil>>, #<Frame:0x00007f9c87833f30 @first_shot=#<Shot:0x00007f9c87833f08 @mark="3">, @second_shot=#<Shot:0x00007f9c87833ee0 @mark="5">, @third_shot=#<Shot:0x00007f9c87833eb8 @mark=nil>>, #<Frame:0x00007f9c87833e90 @first_shot=#<Shot:0x00007f9c87833e68 @mark="X">,...]
```
なので、文字（数字）を配列に格納していると文字（数字）をもとにFrameインスタンスを生成しているとう違いがるのかなと思います

2021-11-24 02:05 UTC, its532 commented on 07.bowling_object/game.rb
> +    score_ary = @game.split(",")
複数使われているわけではないですし、教えていただいたシステムハンガリアンになっていますね
こちら修正します！

2021-11-24 02:05 UTC, its532 commented on 07.bowling_object/game.rb
> +    score_ary.each do |sa|
score_aryの頭文字をとってsaにしていました...
ただ全く意味がわからない変数名になっているので修正します！

2021-11-24 02:05 UTC, its532 commented on 07.bowling_object/game.rb
> +    frame_instances.each_with_index do |frame, i|
パッと良いか書き方が思い付いていないのですが考えてみます！

2021-11-24 02:05 UTC, its532 commented on 07.bowling_object/bowling.rb
> +require_relative './game'
`require_relative`はカレントディレクトリを示す必要がないのですね！
これだた`require`での記述になっていますね...
修正します。

2021-11-24 02:05 UTC, its532 commented on 07.bowling_object/frame.rb
> +  attr_reader :first_shot, :second_shot
`third_shot`については外部からの参照はないので、不要だと思い記述しませんでした。

2021-11-24 02:05 UTC, its532 commented on 07.bowling_object/frame.rb
> +    [first_shot.score + second_shot.score + @third_shot.score].sum
おお、このような書き方もできるのですね。
勉強になります。

2021-11-24 02:05 UTC, its532 commented on 07.bowling_object/shot.rb
> +  end
こちらより簡潔に書けそうですね
ありがとうございます！

2021-11-24 02:10 UTC, its532 commented on 07.bowling_object/game.rb
> +    @game = pin
単純にscoreとかですかね...
自分もパッと思いつかず...

2021-11-24 02:16 UTC, its532 commented on 07.bowling_object/game.rb
> +      frame_instances.push(Frame.new(*frame))
なるほど、そこまで考慮して実装していませんでした...
スコアが変わることはないので毎回インスタンスを作って...みたいなことは不要ですね。

```ruby
@frame_instances ||= frames.each do |frame|
...
```
このような書き方もできるのですね、初めて知りました！
勉強になります。

2021-11-24 02:59 UTC, its532 commented on 07.bowling_object/game.rb
> +  def frame_instances
前提として
`frame_instances`
入力された文字（数字）をもとにFrameクラスのインスタンスを作成して、配列に格納する役割です。

思考の流れとしては
framesという変数名でも良いのでは？
↓
既に変数名として使っているので使えない
↓
Frameクラスのインスタンスを配列に複数作っているのでframe_instanesにする
↓
ただ具体的でなく後から見た人が理解できるのか？
↓
create_frame_instanesはどうだろう？（今考えている）

2021-11-24 07:53 UTC, ikaruga777 commented on 07.bowling_object/game.rb
> +    @game = pin
`result` とかがいいですかねえ。

2021-11-24 08:02 UTC, ikaruga777 commented on 07.bowling_object/game.rb
> +  def frames
なるほど〜、両方とも `Game` クラスの public メソッドになっているのですが、どちらが公開したい情報ですかね。 @its532

2021-11-24 08:20 UTC, its532 commented on 07.bowling_object/game.rb
> +  def frames
ああ、これどちらもpublicでなくとも大丈夫ですね...
これ以外のものもpublicである必要がなさそうなものが多そうです...
@ikaruga777

2021-11-24 08:25 UTC, its532 commented on 07.bowling_object/game.rb
> +    @game = pin
`result`良さそうです！

2021-11-24 09:03 UTC, its532 commented on 07.bowling_object/frame.rb
> +    [first_shot.score + second_shot.score + @third_shot.score].sum
すいませんこの
> @shotsのようにArray

というのがどう実装するかイメージできていないのですが、既にあるinitializeの`@first_shot = Shot.new(first_mark)..`等とは別にinitializeで@shotsというArrayを準備してあげるようなイメージですか？？

2021-11-24 09:03 UTC, its532 commented on 07.bowling_object/frame.rb
> +    [first_shot.score + second_shot.score + @third_shot.score].sum
@komagata

2021-11-25 02:59 UTC, its532 commented
@ikaruga777 @komagata こちら指摘いただいた箇所の修正をしました。
一部不明点がある箇所は質問コメントさせていただいているので、ご確認よろしくお願いいたします:bow:

2021-11-25 09:14 UTC, ikaruga777 commented on 07.bowling_object/game.rb
> +  def result_frame_per_array_storing
このメソッドを生かすのであれば `result_to_array` という名前でもで伝わりそうな気がしています。 (元のメソッド名は `string` のtypoですかね。)

2021-11-25 09:14 UTC, ikaruga777 commented on 07.bowling_object/game.rb
> +    @game = result
変数も `result` にした方がわかりやすいかと思うのですが、いかがでしょう?

2021-11-25 09:35 UTC, its532 commented on 07.bowling_object/game.rb
> +  def result_frame_per_array_storing
@ikaruga777 
resultをフレームごとに配列に格納するという意味合いでこの命名にしました！
> result_to_array という名前でもで伝わりそうな気がしています。

確かにこれでも伝わりそうです！
ただ、フレームごとに配列をつくるという意味合いがある方が分かりやすい気がするので、`result_per_frame_array`とかはどうでしょうか？？

> 元のメソッド名は string のtypoですかね。

これはstoreで格納するという意味でつけたので、typoではないです:bow:

2021-11-25 09:36 UTC, its532 commented on 07.bowling_object/game.rb
> +    @game = result
確かに、resultで合わせた方が分かりやすいですね！
こちら対応します！

2021-11-25 16:33 UTC, komagata requested changes

2021-11-25 16:33 UTC, komagata commented on 07.bowling_object/frame.rb
> +    [first_shot.score + second_shot.score + @third_shot.score].sum
@its532 はい、そうです。

2021-11-26 03:14 UTC, its532 commented on 07.bowling_object/frame.rb
> +    [first_shot.score + second_shot.score + @third_shot.score].sum
ありがとうございます。

2021-11-26 03:14 UTC, its532 commented
@komagata @ikaruga777 
@shots変数の追加とgameという変数名をresultに変更しました。
ご確認よろしくお願いいたします。

2021-11-26 07:36 UTC, ikaruga777 commented on 07.bowling_object/bowling.rb
> +result = Game.new(ARGV[0])
`ARGV[0]` が `result` になると思うので、ここは `game` のままで良いと思います。

2021-11-26 07:52 UTC, ikaruga777 commented on 07.bowling_object/game.rb
> +  def result_frame_per_array_storing
`store` 理解です! それでしたら、 `results_per_frame` にすると良いですね 👍

2021-11-26 08:23 UTC, its532 commented on 07.bowling_object/bowling.rb
> +result = Game.new(ARGV[0])
Gameクラスのインスタンを作るという意味でgameの方が良さそうでした
ありがとうございます！

2021-11-26 09:22 UTC, komagata requested changes

2021-11-26 09:22 UTC, komagata commented on 07.bowling_object/frame.rb
> +    @shots = [@first_shot, @second_shot, @third_shot]
@its532 すみません、僕の説明が足りませんでした。

first_shot, secound_shot, third_shotというもの自体をなくしてshots(Array)にした方が汎用的かなと思った感じです。

ただ、どちらでもいいと思うので、first_shot, second_shot, third_shotの形式を採用するのであればshotsは不要です〜（どちらかがあればいいと思うので）

2021-11-26 09:22 UTC, komagata commented on 07.bowling_object/game.rb
> +  def score
これを変数のように見えるメソッドを使えば、total_scoreというメソッドは不要になるかもです〜。

https://docs.komagata.org/5630

2021-11-26 09:57 UTC, its532 commented on 07.bowling_object/game.rb
> +  def result_frame_per_array_storing
コメントボタン押し忘れていました:bow:
なるほど、arrayの代わりにresultを複数形にするという形の方がスッキリしますね！
> results_per_frame にすると良いですね 

こちらでいこうと思います

2021-11-26 10:09 UTC, its532 commented on 07.bowling_object/frame.rb
> +    @shots = [@first_shot, @second_shot, @third_shot]
自分も実装していて若干違和感を感じたので（わざわざfirst_shot, second_shot, third_shotとしshots二つも作る必要があるのか）、そこ聞いておくべきでした。

ありがとうございます！

> ただ、どちらでもいいと思うので、first_shot, second_shot, third_shotの形式を採用するのであればshotsは不要です〜（どちらかがあればいいと思うので）

他の箇所の変更も必要になりそうなので、first_shot, second_shot, third_shotの形式のままいこうと思います

2021-11-26 10:11 UTC, its532 commented on 07.bowling_object/game.rb
> +  def score
参考urlまでありがとうございます。

試してみます！

2021-11-29 03:07 UTC, its532 commented
@komagata @ikaruga777 
レビューいただいた箇所の修正をしました。ご確認お願いいたします！

2021-11-29 09:31 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-11-30 01:44 UTC, ikaruga777 approved these changes
🙆‍♂️

2021-12-23 10:37 UTC, merged